export const BIBLE_BOOKS = [
    { id: 'genesis', name: 'Genesis' },
    { id: 'exodus', name: 'Exodus' },
    { id: 'leviticus', name: 'Leviticus' },
    { id: 'numbers', name: 'Numbers' },
    { id: 'deuteronomy', name: 'Deuteronomy' },
    { id: 'joshua', name: 'Joshua' },
    { id: 'judges', name: 'Judges' },
    { id: 'ruth', name: 'Ruth' },
    { id: '1samuel', name: '1 Samuel' },
    { id: '2samuel', name: '2 Samuel' },
    { id: '1kings', name: '1 Kings' },
    { id: '2kings', name: '2 Kings' },
    { id: '1chronicles', name: '1 Chronicles' },
    { id: '2chronicles', name: '2 Chronicles' },
    { id: 'ezra', name: 'Ezra' },
    { id: 'nehemiah', name: 'Nehemiah' },
    { id: 'esther', name: 'Esther' },
    { id: 'job', name: 'Job' },
    { id: 'psalms', name: 'Psalms' },
    { id: 'proverbs', name: 'Proverbs' },
    { id: 'ecclesiastes', name: 'Ecclesiastes' },
    { id: 'songofsolomon', name: 'Song of Solomon' },
    { id: 'isaiah', name: 'Isaiah' },
    { id: 'jeremiah', name: 'Jeremiah' },
    { id: 'lamentations', name: 'Lamentations' },
    { id: 'ezekiel', name: 'Ezekiel' },
    { id: 'daniel', name: 'Daniel' },
    { id: 'hosea', name: 'Hosea' },
    { id: 'joel', name: 'Joel' },
    { id: 'amos', name: 'Amos' },
    { id: 'obadiah', name: 'Obadiah' },
    { id: 'jonah', name: 'Jonah' },
    { id: 'micah', name: 'Micah' },
    { id: 'nahum', name: 'Nahum' },
    { id: 'habakkuk', name: 'Habakkuk' },
    { id: 'zephaniah', name: 'Zephaniah' },
    { id: 'haggai', name: 'Haggai' },
    { id: 'zechariah', name: 'Zechariah' },
    { id: 'malachi', name: 'Malachi' },
    { id: 'matthew', name: 'Matthew' },
    { id: 'mark', name: 'Mark' },
    { id: 'luke', name: 'Luke' },
    { id: 'john', name: 'John' },
    { id: 'acts', name: 'Acts' },
    { id: 'romans', name: 'Romans' },
    { id: '1corinthians', name: '1 Corinthians' },
    { id: '2corinthians', name: '2 Corinthians' },
    { id: 'galatians', name: 'Galatians' },
    { id: 'ephesians', name: 'Ephesians' },
    { id: 'philippians', name: 'Philippians' },
    { id: 'colossians', name: 'Colossians' },
    { id: '1thessalonians', name: '1 Thessalonians' },
    { id: '2thessalonians', name: '2 Thessalonians' },
    { id: '1timothy', name: '1 Timothy' },
    { id: '2timothy', name: '2 Timothy' },
    { id: 'titus', name: 'Titus' },
    { id: 'philemon', name: 'Philemon' },
    { id: 'hebrews', name: 'Hebrews' },
    { id: 'james', name: 'James' },
    { id: '1peter', name: '1 Peter' },
    { id: '2peter', name: '2 Peter' },
    { id: '1john', name: '1 John' },
    { id: '2john', name: '2 John' },
    { id: '3john', name: '3 John' },
    { id: 'jude', name: 'Jude' },
    { id: 'revelation', name: 'Revelation' }
];

// Map of English ID -> Localized Name (Display)
export const TELUGU_BOOK_NAMES: Record<string, string> = {
    'genesis': 'ఆదికాండము', 'exodus': 'నిర్గమకాండము', 'leviticus': 'లేవీయకాండము', 'numbers': 'సంఖ్యాకాండము', 'deuteronomy': 'ద్వితీయోపదేశకాండము',
    'joshua': 'యెహొషువ', 'judges': 'న్యాయాధిపతులు', 'ruth': 'రూతు', '1samuel': 'సమూయేలు మొదటి గ్రంథము', '2samuel': 'సమూయేలు రెండవ గ్రంథము',
    '1kings': 'రాజులు మొదటి గ్రంథము', '2kings': 'రాజులు రెండవ గ్రంథము', '1chronicles': 'దినవృత్తాంతములు మొదటి గ్రంథము', '2chronicles': 'దినవృత్తాంతములు రెండవ గ్రంథము',
    'ezra': 'ఎజ్రా', 'nehemiah': 'నెహెమ్యా', 'esther': 'ఎస్తేరు', 'job': 'యోబు గ్రంథము', 'psalms': 'కీర్తనల గ్రంథము', 'proverbs': 'సామెతలు',
    'ecclesiastes': 'ప్రసంగి', 'songofsolomon': 'పరమగీతము', 'isaiah': 'యెషయా గ్రంథము', 'jeremiah': 'యిర్మీయా', 'lamentations': 'విలాపవాక్యములు',
    'ezekiel': 'యెహెజ్కేలు', 'daniel': 'దానియేలు', 'hosea': 'హోషేయ', 'joel': 'యోవేలు', 'amos': 'ఆమోసు', 'obadiah': 'ఓబద్యా',
    'jonah': 'యోనా', 'micah': 'మీకా', 'nahum': 'నహూము', 'habakkuk': 'హబక్కూకు', 'zephaniah': 'జెఫన్యా', 'haggai': 'హగ్గయి',
    'zechariah': 'జెకర్యా', 'malachi': 'మలాకీ',
    'matthew': 'మత్తయి సువార్త', 'mark': 'మార్కు సువార్త', 'luke': 'లూకా సువార్త', 'john': 'యోహాను సువార్త', 'acts': 'అపొస్తలుల కార్యములు',
    'romans': 'రోమీయులకు', '1corinthians': '1 కొరింథీయులకు', '2corinthians': '2 కొరింథీయులకు', 'galatians': 'గలతీయులకు', 'ephesians': 'ఎఫెసీయులకు',
    'philippians': 'ఫిలిప్పీయులకు', 'colossians': 'కొలొస్సయులకు', '1thessalonians': '1 థెస్సలొనీకయులకు', '2thessalonians': '2 థెస్సలొనీకయులకు',
    '1timothy': '1 తిమోతికి', '2timothy': '2 తిమోతికి', 'titus': 'తీతుకు', 'philemon': 'ఫిలేమోనుకు', 'hebrews': 'హెబ్రీయులకు', 'james': 'యాకోబు',
    '1peter': '1 పేతురు', '2peter': '2 పేతురు', '1john': '1 యోహాను', '2john': '2 యోహాను', '3john': '3 యోహాను', 'jude': 'యూదా', 'revelation': 'ప్రకటన గ్రంథము'
};

// Map of English ID -> Folder Name (API Path)
// Inferring based on "First Word" or common abbreviation seen in repo
export const TELUGU_FOLDER_MAPPINGS: Record<string, string> = {
    'genesis': 'ఆది', 'exodus': 'నిర్గమ', 'leviticus': 'లేవీ', 'numbers': 'సంఖ్యా', 'deuteronomy': 'ద్వితీ',
    'joshua': 'యెహొషువ', 'judges': 'న్యాయాధిపతులు', 'ruth': 'రూతు',
    '1samuel': '1సమూయేలు', '2samuel': '2సమూయేలు', // Guessing digits prefix
    '1kings': '1రాజులు', '2kings': '2రాజులు',
    '1chronicles': '1దిన', '2chronicles': '2దిన', // Guessing abbreviation
    'ezra': 'ఎజ్రా', 'nehemiah': 'నెహెమ్యా', 'esther': 'ఎస్తేరు',
    'job': 'యోబు', 'psalms': 'కీర్తనలు', 'proverbs': 'సామెత', // "సామెత" (Sameta) - Proverb
    'ecclesiastes': 'ప్రసంగి', 'songofsolomon': 'పరమ',
    'isaiah': 'యెషయా', 'jeremiah': 'యిర్మీయా', 'lamentations': 'విలాప', // "విలాప" (Vilapa)
    'ezekiel': 'యెహెజ్కేలు', 'daniel': 'దానియేలు',
    'hosea': 'హోషే', 'joel': 'యోవేలు', 'amos': 'ఆమోసు', 'obadiah': 'ఓబద్యా',
    'jonah': 'యోనా', 'micah': 'మీకా', 'nahum': 'నహూము', 'habakkuk': 'హబక్కూకు', 'zephaniah': 'జెఫ', // Guessing
    'haggai': 'హగ్గయి', 'zechariah': 'జెకర్యా', 'malachi': 'మలాకీ',
    'matthew': 'మత్తయి', 'mark': 'మార్కు', 'luke': 'లూకా', 'john': 'యోహాను', 'acts': 'అపొ', // Guessing
    'romans': 'రోమీ', '1corinthians': '1కొరింథీ', '2corinthians': '2కొరింథీ',
    'galatians': 'గలతీ', 'ephesians': 'ఎఫెసీ', 'philippians': 'ఫిలిప్పీ', 'colossians': 'కొలొ',
    '1thessalonians': '1థెస్స', '2thessalonians': '2థెస్స',
    '1timothy': '1తిమోతి', '2timothy': '2తిమోతి', 'titus': 'తీతు', 'philemon': 'ఫిలే',
    'hebrews': 'హెబ్రీ', 'james': 'యాకోబు',
    '1peter': '1పేతురు', '2peter': '2పేతురు',
    '1john': '1యోహాను', '2john': '2యోహాను', '3john': '3యోహాను',
    'jude': 'యూదా', 'revelation': 'ప్రకటన'
};

// Hindi Mappings (Similar logic)
export const HINDI_BOOK_NAMES: Record<string, string> = {
    'genesis': 'उत्पत्ति', 'exodus': 'निर्गमन', 'leviticus': 'लैव्यव्यवस्था', 'numbers': 'गिनती', 'deuteronomy': 'व्यवस्थाविवरण',
    'joshua': 'यहोशू', 'judges': 'न्यायियों', 'ruth': 'रूत', '1samuel': '1 शमूएल', '2samuel': '2 शमूएल',
    '1kings': '1 राजा', '2kings': '2 राजा', '1chronicles': '1 इतिहास', '2chronicles': '2 इतिहास',
    'ezra': 'एज्रा', 'nehemiah': 'नहेमायाह', 'esther': 'एस्तेर', 'job': 'अय्यूब', 'psalms': 'भजन संहिता', 'proverbs': 'नीतिवचन',
    'ecclesiastes': 'सभोपदेशक', 'songofsolomon': 'श्रेष्ठगीत', 'isaiah': 'यशायाह', 'jeremiah': 'यिर्मयाह', 'lamentations': 'विलापगीत',
    'ezekiel': 'यहेजकेल', 'daniel': 'दानिय्येल', 'hosea': 'होशे', 'joel': 'योएल', 'amos': 'आमोस', 'obadiah': 'ओबद्याह',
    'jonah': 'योना', 'micah': 'मीका', 'nahum': 'नहूम', 'habakkuk': 'हबक्कूक', 'zephaniah': 'सपन्याह', 'haggai': 'हाग्गै',
    'zechariah': 'जकरयाह', 'malachi': 'मलाकी',
    'matthew': 'मत्ती', 'mark': 'मरकुस', 'luke': 'लूका', 'john': 'यूहन्‍ना', 'acts': 'प्रेरितों के काम',
    'romans': 'रोमियों', '1corinthians': '1 कुरिन्थियों', '2corinthians': '2 कुरिन्थियों', 'galatians': 'गलातियों', 'ephesians': 'इफिसियों',
    'philippians': 'फिलिप्पियों', 'colossians': 'कुलुस्सियों', '1thessalonians': '1 थिस्सलुनीकियों', '2thessalonians': '2 थिस्सलुनीकियों',
    '1timothy': '1 तीमुथियुस', '2timothy': '2 तीमुथियुस', 'titus': 'तीतुस', 'philemon': 'फिलेमोन', 'hebrews': 'इब्रानियों', 'james': 'याकूब',
    '1peter': '1 पतरस', '2peter': '2 पतरस', '1john': '1 यूहन्‍ना', '2john': '2 यूहन्‍ना', '3john': '3 यूहन्‍ना', 'jude': 'यहूदा', 'revelation': 'प्रकाशितवाक्य'
};

export const HINDI_FOLDER_MAPPINGS: Record<string, string> = {
    'genesis': 'उत्पत्ति', 'exodus': 'निर्गमन', 'leviticus': 'लैव्यव्यवस्था', 'numbers': 'गिनती', 'deuteronomy': 'व्यवस्थाविवरण',
    'joshua': 'यहोशू', 'judges': 'न्यायियों', 'ruth': 'रूत',
    '1samuel': '1शमूएल', '2samuel': '2शमूएल',
    '1kings': '1राजा', '2kings': '2राजा',
    '1chronicles': '1इतिहास', '2chronicles': '2इतिहास',
    'ezra': 'एज्रा', 'nehemiah': 'नहेमायाह', 'esther': 'एस्तेर',
    'job': 'अय्यूब', 'psalms': 'भजन', 'proverbs': 'नीतिवचन',
    'ecclesiastes': 'सभोपदेशक', 'songofsolomon': 'श्रेष्ठगीत',
    'isaiah': 'यशायाह', 'jeremiah': 'यिर्मयाह', 'lamentations': 'विलापगीत',
    'ezekiel': 'यहेजकेल', 'daniel': 'दानिय्येल',
    'hosea': 'होशे', 'joel': 'योएल', 'amos': 'आमोस', 'obadiah': 'ओबद्याह',
    'jonah': 'योना', 'micah': 'मीका', 'nahum': 'नहूम', 'habakkuk': 'हबक्कूक', 'zephaniah': 'सपन्याह', 'haggai': 'हाग्गै',
    'zechariah': 'जकरयाह', 'malachi': 'मलाकी',
    'matthew': 'मत्ती', 'mark': 'मरकुस', 'luke': 'लूका', 'john': 'यूहन्‍ना', 'acts': 'प्रेरितों',
    'romans': 'रोमियों', '1corinthians': '1कुरिन्थियों', '2corinthians': '2कुरिन्थियों',
    'galatians': 'गलातियों', 'ephesians': 'इफिसियों', 'philippians': 'फिलिप्पियों', 'colossians': 'कुलुस्सियों',
    '1thessalonians': '1थिस्सलुनीकियों', '2thessalonians': '2थिस्सलुनीकियों',
    '1timothy': '1तीमुथियुस', '2timothy': '2तीमुथियुस', 'titus': 'तीतुस', 'philemon': 'फिलेमोन',
    'hebrews': 'इब्रानियों', 'james': 'याकूब',
    '1peter': '1पतरस', '2peter': '2पतरस',
    '1john': '1यूहन्‍ना', '2john': '2यूहन्‍ना', '3john': '3यूहन्‍ना',
    'jude': 'यहूदा', 'revelation': 'प्रकाशितवाक्य'
};
